Universe = vanilla
Notification = Complete
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy
accounting_group = group_atlas.boulder



#Executable = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/bin/z_gen
#
#Arguments = 1 5020 2.5 20000 rootFiles/z_gen_sqrts5020GeV.root
#Log = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/logs/z_gen_sqrts5020GeV.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/outputs/z_gen_sqrts5020GeV.out
#Error = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/errors/z_gen_sqrts5020GeV.err
#Queue 1
#
#Arguments = 1 8160 2.5 20000 rootFiles/z_gen_sqrts8160GeV.root
#Log = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/logs/z_gen_sqrts8160GeV.log
#Output = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/outputs/z_gen_sqrts8160GeV.out
#Error = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/errors/z_gen_sqrts8160GeV.err
#Queue 1



Executable = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/bin/photon_gen

Arguments = 1 5020 40 20000 rootFiles/photon_gen_sqrts5020GeV.root
Log = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/logs/photon_gen_sqrts5020GeV.log
Output = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/outputs/photon_gen_sqrts5020GeV.out
Error = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/errors/photon_gen_sqrts5020GeV.err
Queue 1

Executable = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/bin/photon_gen
Arguments = 1 8160 40 20000 rootFiles/photon_gen_sqrts8160GeV.root
Log = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/logs/photon_gen_sqrts8160GeV.log
Output = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/outputs/photon_gen_sqrts8160GeV.out
Error = /atlasgpfs01/usatlas/workarea/jeff/PythiaCoMStudy/errors/photon_gen_sqrts8160GeV.err
Queue 1

